@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
hide empty members

Tr4cker *-right-> "1" UniqueTaskList
Tr4cker *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueTaskList
UniqueTagList -[hidden]down- UniqueTaskList

UniqueTagList *-right-> "*" Tag
UniqueTaskList o-right-> Task

Task -up-> "*" Tag

Task *--> CompletionStatus
Task *--> Deadline
Task *--> Name
Task *--> TaskDescription
@enduml
