@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTr4cker <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Tr4cker
Class ReadOnlyTr4cker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Task {
Class Task
Class CompletionStatus
Class Deadline
Class Name
Class TaskDescription
Class UniqueTaskList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Tr4cker .up.|> ReadOnlyTr4cker

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Tr4cker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Tr4cker *--> "1" UniqueTaskList
UniqueTaskList o--> "*" Task
Task *--> CompletionStatus
Task *--> Deadline
Task *--> Name
Task *--> TaskDescription
Task *--> "*" Tag

Name -[hidden]right-> Deadline
Deadline -[hidden]right-> TaskDescription
TaskDescription -[hidden]right-> CompletionStatus

ModelManager -->"1" Task : filtered list
@enduml
