@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR
hide empty members

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface Tr4ckerStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonTr4ckerStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> Tr4ckerStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonTr4ckerStorage .left.|> Tr4ckerStorage
JsonTr4ckerStorage .down.> JsonSerializableTr4ckerStorage
JsonSerializableTr4ckerStorage .right.> JsonSerializableTask
JsonSerializableTask .right.> JsonAdaptedTag
@enduml
